### ISSUE TITLE
Sensors.Dht\Sensors.Dht.vcxproj incompatible with Visual Studio 2017

### ISSUE THREAD

**Issue by MfCAYO** [porrey/dht#3]
hello,
when i try to open Windows 10 IoT Core - DHT Solution by the new Visual Studio 2017 i receiving this error message...

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Sensors.Dht, "C:\Users\myUser\Documents\Visual Studio 2015\Projects\DHT Solution\Sensors.Dht\Sensors.Dht.vcxproj"

Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - DHT Solution, "C:\Users\myUser\Documents\Visual Studio 2015\Projects\DHT Solution\DHT Solution.sln"

but the error persists and the project doesn't load...

Sensors.Dht\Sensors.Dht.vcxproj: The application which this project type is based on was not found. Please try this link for further information: [https://go.microsoft.com/fwlink/?LinkId=660147&projecttype=8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942](url)

thank you for your help

**Comment by MfCAYO** [comment]
Problem solved by the repair operation of Visual Studio.

**Comment by porrey** [comment]
Thanks for posting the follow-up.
