### ISSUE TITLE
Could not find Windows Runtime type 'Sensors.Dht.Dht22'

### ISSUE THREAD

**Issue by RichieRogers** [porrey/dht#4]
Hi,
I've installed from Nuget onto Visual Studio 2017, but I'm unable to get it to work.
I get the following error:
"Could not find Windows Runtime type 'Sensors.Dht.Dht22'"
I've used the code example on the readme page.

Any ideas how to resolve?
Rapsberry Pi 3
Visual Studio 2017

Thanks,
Richie

**Comment by porrey** [comment]
The original NuGet package was not created correctly. It worked previously but seemed to stop working in VS2017. I updated the library in VS 2017, recompiled and created a new NuGet package. Please update the package and let me know if your problem is resolved or not.

**Comment by RichieRogers** [comment]
Hi,
Updated and no longer get the error... well, no error with your mode - my code, on the other hand, throws some errors, but that's something I'll have to fix lol.
Thanks,
Richie

**Comment by RichieRogers** [comment]
Just to confirm that I've fixed my code as well and the device reads correctly now.
Thanks,
Richie
