### ISSUE TITLE
the Dht c# library is not installing on my Visual Studio project

### ISSUE THREAD

**Issue by dinoToribio** [porrey/dht#5]
when i try to install the Dht C# Library, Visual Studio display an error like this: 

Could not install package 'Dht 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What should i do to fix this?

i used Visual studio 2015 and the .netframework version of my project "v.4.5.2".

thank you in advance.

**Comment by porrey** [comment]
This package can only be used with a UWP application. If you are building an IoT solution, use a Universal Windows project instead of a .NET application.
